services:
  dev:
    tty: true
    hostname: devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
      args:
        PROJECT_NAME: valheim-vrm
    volumes:
      # Workspace
      - ..:/workspace/valheim-vrm:cached
      # Home
      - ../volumes/home:/home/vscode:cached
      # Additional scripts
      - ~/scripts:/home/vscode/scripts:ro
